n_phases: 10
timesteps_per_phase: 200_000
eval_episodes: 100
convergence_threshold: 0.10
n_seeds: 5

# Health monitor thresholds
health:
  min_entropy: 0.1
  max_capture_rate: 0.90
  min_capture_rate: 0.10
  greedy_eval_interval: 2
  max_checkpoints: 5
